[package]
name = "json"
version = "0.1.0"
edition = "2021"

[lib]
name = "json"
path = "src/lib.rs"

[dependencies]
thiserror = "1.0"
json_macro = { path = "../json_macro" }

[[bin]]
name = "jsonbin"
path = "src/bin.rs"
